name: bug-prediction-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - scipy
  - scikit-learn
  - numpy
  - jupyter
  - matplotlib
  - seaborn
  - nltk
  - wordcloud
  - xgboost
  - lightgbm
  - imbalanced-learn
  - plotly
  - requests
  - fastapi
  - uvicorn
  - streamlit
  - joblib
  - pip
  - pip:
      - transformers
      - datasets
      - torch