name: bug-prediction-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - requests
  - fastapi
  - uvicorn
  - streamlit
  - plotly
  - sqlite
  - pip
  - pip:
      - torch
      - transformers
      - pydantic